[package]
name = "advent_of_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adjacent-pair-iterator = "1.0.0"
nom = "7.1.1"
